#!/usr/bin/env sh
# bootstrap: populate home directory: create initial environment symlinks.
# This file belongs to andrzejc/homedir: git@github.com:andrzejc/homedir.git
set -e
set -x

HOMEDIR=$(realpath $(dirname $0))

# Pathogen install into ~/.vim/autoload
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Clone or update vim plugin repos
cat $HOMEDIR/vim-bundles | sed -e 's/#.*$//' -e '/^\w*$/d' | \
	while read repo; do
		name=`basename $repo | sed s/\\.git$//`
		bundledir="$HOME/.vim/bundle/$name"
		if [ -d "$bundledir" ]; then
			pushd "$bundledir"
			git pull --quiet || echo "warning: git pull failed for $bundledir"
			popd
		else
			git clone "$repo" "$bundledir"
		fi
	done

# Install .git-prompt.sh into ~/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
	-o ~/.git-prompt.sh

# Install tmux plugin manager
[ -d "$HOME/.tmux/plugins/tpm" ] || \
	git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"

# Install rc files symlinks into ~/
LINKS=".profile .bashrc .bash_profile .vimrc .tmux.conf .tmux.conf.theme \
.ansi-colors.sh"

for x in ${LINKS}; do
	src="$HOMEDIR/$x"
	dst="$HOME/$x"
	# Only if $dst doesn't already point to $src
	if [[ (! -e "${dst}") || (! "${dst}" -ef "${src}") ]]; then
		# Symlink, with confirmation if already exists
		ln -siv "${src}" "${dst}"
	fi
done
